


exchange = 'Kucoin.com'

# Kucoin.com
kucoin_key = ''
kucoin_secret = ''
kucoin_pasw = ''
tf = 5  # 1,5,15,30,60,120,240,480,720,1440,10080
'''
['XBTUSDTM', 'XBTUSDM', 'ETHUSDTM', 'BCHUSDTM', 'BSVUSDTM', 'LINKUSDTM', 'UNIUSDTM', 'YFIUSDTM', 
'EOSUSDTM', 'DOTUSDTM', 'FILUSDTM', 'ADAUSDTM', 'XRPUSDTM', 'LTCUSDTM', 'ETHUSDM', 'TRXUSDTM', 
'GRTUSDTM', 'SUSHIUSDTM', 'XLMUSDTM', '1INCHUSDTM', 'ZECUSDTM', 'DASHUSDTM', 'DOTUSDM', 'XRPUSDM', 
'AAVEUSDTM', 'KSMUSDTM', 'DOGEUSDTM', 'VETUSDTM', 'BNBUSDTM', 'SXPUSDTM', 'SOLUSDTM', 'IOSTUSDTM', 
'CRVUSDTM', 'ALGOUSDTM', 'AVAXUSDTM', 'FTMUSDTM', 'MATICUSDTM', 'THETAUSDTM', 'ATOMUSDTM', 'CHZUSDTM', 
'ENJUSDTM', 'MANAUSDTM', 'DENTUSDTM', 'OCEANUSDTM', 'BATUSDTM', 'XEMUSDTM', 'QTUMUSDTM', 'XTZUSDTM', 
'SNXUSDTM', 'NEOUSDTM', 'ONTUSDTM', 'XMRUSDTM', 'COMPUSDTM', 'ETCUSDTM', 'WAVESUSDTM', 'BANDUSDTM', 
'MKRUSDTM', 'RVNUSDTM', 'DGBUSDTM', 'MIRUSDTM', 'SHIBUSDTM', 'ICPUSDTM', 'DYDXUSDTM', 'AXSUSDTM', 
'HBARUSDTM', 'EGLDUSDTM', 'ALICEUSDTM', 'YGGUSDTM', 'NEARUSDTM', 'SANDUSDTM', 'C98USDTM', 'ONEUSDTM', 
'VRAUSDTM', 'GALAUSDTM', 'TLMUSDTM', 'CHRUSDTM', 'LRCUSDTM', 'FLOWUSDTM', 'RNDRUSDTM', 'IOTXUSDTM', 
'CROUSDTM', 'WAXPUSDTM', 'PEOPLEUSDTM', 'OMGUSDTM', 'LINAUSDTM', 'IMXUSDTM', 'NFTUSDTM', 'CELRUSDTM', 
'ENSUSDTM', 'CELOUSDTM', 'CTSIUSDTM', 'SLPUSDTM', 'ARPAUSDTM', 'KNCUSDTM', 'SOSUSDTM', 'API3USDTM', 
'ROSEUSDTM', 'AGLDUSDTM', 'APEUSDTM', 'JASMYUSDTM', 'ZILUSDTM', 'GMTUSDTM', 'RUNEUSDTM', 'NYMUSDTM', 
'LOOKSUSDTM', 'AUDIOUSDTM', 'KDAUSDTM', 'KAVAUSDTM', 'BALUSDTM', 'GALUSDTM', 'LUNAUSDTM', 'LUNCUSDTM', 
'OPUSDTM', 'XCNUSDTM', 'UNFIUSDTM', 'LITUSDTM', 'DUSKUSDTM', 'STORJUSDTM', 'ANCUSDTM', 'RSRUSDTM', 
'JSTUSDTM', 'OGNUSDTM', 'TRBUSDTM', 'PERPUSDTM', 'KLAYUSDTM', 'ANKRUSDTM', 'LDOUSDTM', 'WOOUSDTM', 
'RENUSDTM', 'CVCUSDTM', 'INJUSDTM', 'APTUSDTM', 'MASKUSDTM', 'REEFUSDTM', 'XBTMZ22']
'''
whait_list = ['ADAUSDTM', ]


